apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomization
namespace: tigera-operator

resources:
- namespace.yaml

helmGlobals:
  chartHome: ../../helmCharts/

helmCharts:
- includeCRDs: true
  name: tigera-operator
  repo: https://docs.tigera.io/calico/charts
  version: 3.30.1
  releaseName: calico
  namespace: tigera-operator
  valuesFile: values.yaml


generatorOptions:
  disableNameSuffixHash: true
